# Numpy

In [1]:
## importing numpy lib
import numpy as np

In [29]:
## create list
my_list =[1,2,3,4]

## create array with list
my_arr = np.array(my_list)

In [31]:
## finding datatype
type(my_arr)

numpy.ndarray

In [32]:
## checking array shape
my_arr.shape

(4,)

In [33]:
my_arr

array([1, 2, 3, 4])

In [34]:
print(my_arr)

[1 2 3 4]


In [35]:
## creating multilist
my_list1=[11,12,13,14]
my_list2=[21,22,23,24]
my_list3=[31,32,33,34]

In [36]:
## creating MultiDimentional Array
my_arr=np.array([my_list1,my_list2,my_list3])

In [37]:
my_arr

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [38]:
## checking the shape of the array
my_arr.shape

(3, 4)

## Re-shape Array

In [39]:
## re-shaping the array
my_arr.reshape(4,3)

array([[11, 12, 13],
       [14, 21, 22],
       [23, 24, 31],
       [32, 33, 34]])

In [40]:
## re-shaping the array
my_arr.reshape(1,12)

array([[11, 12, 13, 14, 21, 22, 23, 24, 31, 32, 33, 34]])

## Indexing

In [43]:
## create list
my_list = [1,2,3]
my_list

[1, 2, 3]

In [45]:
## creating array from list
my_arr = np.array(my_list)
type(my_arr)

numpy.ndarray

In [48]:
## retrive data using index
my_arr[2]

3

In [62]:
## creating multiple list
my_list1=[11,12,13,14,15]
my_list2=[21,22,23,24,25]
my_list3=[31,32,33,34,35]

##creating 2-dimensional array
my_arr=np.array([my_list1,my_list2,my_list3])

##print array
my_arr

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35]])

In [63]:
## Retrive using index colon
my_arr[:,:]

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35]])

In [64]:
## retrive using index
my_arr[1:,2:4]

array([[23, 24],
       [33, 34]])

In [65]:
## retrive using index
my_arr[1:2,1:4]

array([[22, 23, 24]])

## Arange()

In [66]:
## print my_arr
my_arr

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35]])

In [67]:
## using arange() with array
my_arr = np.arange(11,23)

In [59]:
## print my_arr
my_arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [68]:
## using arange() with step
my_arr = np.arange(12,23,step=2)

## print my_arr
my_arr

array([12, 14, 16, 18, 20, 22])

## linspace()

In [70]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

## copy()

In [71]:
## using copy() - copying array in another varaiable
arr1=my_arr.copy()

##print arr1
arr1

array([12, 14, 16, 18, 20, 22])

In [73]:
## copying using copy() function and broadcasting
arr2=my_arr.copy()

##print arr2
arr2

array([12, 14, 16, 18, 20, 22])

In [76]:
## broadcasting - replacing the array values 
arr2[3:]=100

## print arr2
arr2

array([ 12,  14,  16, 100, 100, 100])

In [77]:
## print my_arr
my_arr

array([12, 14, 16, 18, 20, 22])

In [78]:
## copying array without copy() function abd broadcasting
arr3=my_arr

## print arr3
print("my_arr - before Broadcasting")
print(my_arr)
print("arr3 - before Broadcasting")
print(arr3)

## apply broadcasting
arr3[2:]=400

## print arr3
print("my_arr - after Broadcasting")
print(my_arr)
print("arr3 - after Broadcasting")
print(arr3)


my_arr - before Broadcasting
[12 14 16 18 20 22]
arr3 - before Broadcasting
[12 14 16 18 20 22]
my_arr - after Broadcasting
[ 12  14 400 400 400 400]
arr3 - after Broadcasting
[ 12  14 400 400 400 400]


## Condition useful in Exploratory Data Analysis

In [80]:
## creating MultiDimentional Array
my_arr=np.array([my_list1,my_list2,my_list3])

##Print Array
my_arr

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35]])

In [81]:
## checking the values in the array for <30
my_arr<30

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False]])

In [83]:
## multiply array with 2
my_arr*2

array([[22, 24, 26, 28, 30],
       [42, 44, 46, 48, 50],
       [62, 64, 66, 68, 70]])

In [85]:
## divide array with 2
val = 2
my_arr/val

array([[ 5.5,  6. ,  6.5,  7. ,  7.5],
       [10.5, 11. , 11.5, 12. , 12.5],
       [15.5, 16. , 16.5, 17. , 17.5]])

## ones()

In [93]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

## Random Distribution

In [97]:
np.random.rand(2,3)

array([[0.26509012, 0.07587042, 0.44918894],
       [0.24319824, 0.11884388, 0.83746569]])

In [98]:
np.random.randn(2,3)

array([[-0.04021108, -0.31478228, -1.16029007],
       [-0.12044641, -0.06578777,  1.60395626]])

In [111]:
np.random.randint(0,100,8).reshape(2,4)

array([[70, 58, 25, 85],
       [25, 10, 88,  8]])