## K Flod Cross Validation

In [18]:
#import library
import pandas as pd
import numpy as np

In [1]:
# load dataset
from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
dir(iris)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [6]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
df['target']=iris.target
df.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                5.1               3.5  ...               0.2       0
1                4.9               3.0  ...               0.2       0
2                4.7               3.2  ...               0.2       0
3                4.6               3.1  ...               0.2       0
4                5.0               3.6  ...               0.2       0

[5 rows x 5 columns]

In [11]:
# import Cross Val
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier 
from sklearn.ensemble import RandomForestClassifier

In [17]:
log = cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),df.drop('target',axis=1),df.target)
log

array([1.        , 0.96666667, 0.93333333, 0.9       , 1.        ])

In [39]:
print('LogisticRegression score is {}'.format(np.average(log)))

LogisticRegression score is 0.9600000000000002


In [29]:
svc = cross_val_score(SVC(gamma='auto'),df.drop('target',axis=1),df.target)
svc

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [42]:
print('SVC score is {}'.format(np.average(svc)))

SVC score is 0.9800000000000001


In [25]:
dt=cross_val_score(DecisionTreeClassifier(),df.drop('target',axis=1),df.target)
dt

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [41]:
print('Decision score is {}'.format(np.average(dt)))

Decision score is 0.9666666666666668


In [49]:
rf=cross_val_score(RandomForestClassifier(n_estimators=45),df.drop('target',axis=1),df.target)
rf

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [50]:
print('RandomForest score is {}'.format(np.average(rf)))

RandomForest score is 0.9666666666666668
